version: '3.1'
services:
  web:
    image: odoo:18.0
    depends_on:
      - postgres-16
    ports:
      - "6666:8069"
    volumes:
      - odoo-data-volume:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  postgres-16:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data-volume:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-data-volume:
  db-data-volume:

secrets:
  postgresql_password:
    file: ./config/odoo_pg_pass

